# Traefik Ingress resource defining routing rules and TLS entrypoints.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foobar-ingress
  namespace: foobar-namespace
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  tls:
    - hosts:
        - foobar.local
      # ARCHITECT TIP: No secretName here forces Traefik to use the PVC certs
  rules:
  - host: foobar.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foobar-service
            port:
              number: 443