# certificate storage (128Mi, local-path)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-certs-pvc
  namespace: foobar-namespace
spec:
  accessModes:
    - ReadWriteOnce
  # use empty string for local/standard testing
  # use the default provisioner, or specify 'standard' for Minikube/Kind
  # since Im using Rancher for testing, it needs to be explicitly set as 'local-path'
  storageClassName: "local-path" 
  resources:
    requests:
      storage: 128Mi