apiVersion: v1
kind: Service
metadata:
  name: foobar-service
  namespace: foobar-namespace
spec:
  selector:
    app: foobar-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80 # Alignment: Points to the app's port 80